#!/usr/bin/env node

const program = require('commander');
const clear = require('clear');
const chalk = require('chalk');
const figlet = require('figlet');
const packageJson = require('../package.json');

// Lets clear the console
clear();

// banner of the cli
console.info(
  chalk.yellow(figlet.textSync(packageJson.name, {horizontalLayout: 'full'}))
);
console.info(chalk.cyan('Version: ' + packageJson.version));


program
  .version(packageJson.version)
  .description(packageJson.description)
  .command('init', 'Initialize the project with development version')
  .command('create-branch', 'Create the branch from master branch')
  .command('release', 'Create release tag on a release branch')
  .parse(process.argv);

// dispay the usage
if (!program.args.length) program.help();
